(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

(* NotImplementedYet *)

Definition main (_ : unit) : unit :=
  let _ := e_print (impl_2__new_const (["Hello, world!
"%string])) in
  let _ := tt in
  let name := "Rust"%string in
  let _ := e_print (impl_2__new_v1 (["Hello, "%string; "!
"%string]) ([impl_1__new_display (name)])) in
  let _ := tt in
  let _ := e_print (impl_2__new_v1 (["Hello, Macro!
"%string]) (impl_1__none (tt))) in
  let _ := tt in
  tt.
