(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.



(* NotImplementedYet *)

Definition main (_ : unit) : unit :=
  tt.

Definition haha (x : t_i32) : t_i32 :=
  run (let hoist1 := ControlFlow_Break (x) in
  ControlFlow_Continue (never_to_any (hoist1))).
