(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition main (_ : unit) : unit :=
  let x : (t_i32*t_i32*t_i32) := (6,5,4) in
  let x1 := TODO: please implement the method `expr'_App_tuple_projection` in
  let x2 := TODO: please implement the method `expr'_App_tuple_projection` in
  let x3 := TODO: please implement the method `expr'_App_tuple_projection` in
  tt.
