(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.



(* NotImplementedYet *)

Definition main (_ : unit) : unit :=
  let x1 := -9.31%float in
  let x2 := f_ge (17) (2) in
  let x3 := true in
  let x4 := false in
  let x5 := "c"%char in
  let x6 := f_from ("Hello"%string) in
  tt.
