(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.



(* NotImplementedYet *)

Class t_Summary `{v_Self : Type} : Type :=
  {
    f_sum : Type;
    _ :: `{t_Sized (f_sum)};
    f_summarize : v_Self -> t_i32;
  }.
Arguments t_Summary:clear implicits.
Arguments t_Summary (_).
